- arguments: [--cpp-include=src/full]

# - extensions:
#   - default: false # all extension are banned by default
#   - name: [PatternGuards, ViewPatterns] # only these listed extensions can be used
#   - {name: CPP, within: CrossPlatform} # CPP can only be used in a given module
#
# - flags:
#   - {name: -w, within: []} # -w is allowed nowhere
#
# - modules:
#   - {name: [Data.Set, Data.HashSet], as: Set} # if you import Data.Set qualified, it must be as 'Set'
#   - {name: Control.Arrow, within: []} # Certain modules are banned entirely
#
# - functions:
#   - {name: unsafePerformIO, within: []} # unsafePerformIO can only appear in no modules

# - error: {lhs: "wibbleMany [x]", rhs: wibbleOne x}

- group: {name: dollar, enabled: true}
# - group: {name: generalise, enabled: true}
# - warn: {name: Use explicit module export list}

# Define some custom infix operators
# - fixity: infixr 3 ~^#^~
