[package]
name = "owo"
version = "0.1.0"
authors = ["ice1000 <ice1000kotlin@foxmail.com>"]
edition = "2018"

[dependencies]
symmetric-interaction-calculus = { git = "https://github.com/owo-lang/Symmetric-Interaction-Calculus" }
