version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Nightly Build
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      # - run:
          # name: Upload Coverage
          # command: ./scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - "/usr/local/cargo/registry"
            - "~/.cargo"
            - "./target"
