version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-demo-haskell-v1-{{ checksum "OwO.cabal" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Install alex
          command: stack install alex
      - run:
          name: Install executable
          command: stack install
      - store_artifacts:
          path: ~/.local/bin/owo
          destination: owo
      - run:
          name: Install hlint
          command: stack install hlint
      - save_cache:
          name: Cache Dependencies
          key: cci-demo-haskell-v1-{{ checksum "OwO.cabal" }}
          paths:
            - ".stack-work"
            - "~/.cabal"
            - "~/.stack"
      - run:
          name: Run hlint, ignoring errors
          command: hlint src || true
      - run:
          name: Run tests
          command: |
            cd src/test/testData
            perl --version
            perl test_runner.pl --force
            cd -
