version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-demo-haskell-v1-{{ checksum "OwO.cabal" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      # - run:
          # name: Run tests
          # command: stack test
      - run:
          name: Install executable
          command: stack install
      - save_cache:
          name: Cache Dependencies
          key: cci-demo-haskell-v1-{{ checksum "OwO.cabal" }}
          paths:
            - ".stack-work"
      - store_artifacts:
          path: ~/.local/bin/owo
          destination: owo
      - run:
          name: Install hlint
          command: stack install hlint
      - run:
          name: Run hlint
          command: hlint src --cpp-include=src/full
